import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarPage from "@/componets/Navbar";
import Footer from "@/componets/Footer";
import toast, { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Sports Nest ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavbarPage></NavbarPage>
        {children}
        <Footer></Footer>
        <Toaster />
        </body>
    </html>
  );
}
